### Tạo đơn hàng
POST http://localhost:3000/donhang
Content-Type: application/json

{
  "tenSanPham": "Xoài cát Hòa Lộc",
  "soLuong": 3,
  "tongTien": 90000,
  "ngayBan": "2025-10-26"
}

GET http://localhost:3000/donhang/search?from=2025-10-01&to=2025-10-26
